### ISSUE TITLE
Summary-level data

### ISSUE THREAD

**Issue by biolyn** [rahulg603/mtSwirl#7]
Hi rahulg,
I tried to find the Summary statistics from UKB either via GWAS Catalog or on Google Cloud Platform, but I failed.
In GWAS Catalog, I can not find the resource under ID GCP000614.
On Google Cloud Platform, I do not have access, as shown in the picture below.
How could I apply for the summary-level GWAS data?
Thanks!

Regard,
Lyn

![image](https://github.com/rahulg603/mtSwirl/assets/81401680/6d645434-a843-4717-8ad8-c18fb12e2405)

**Comment by rahulg603** [comment]
Hi Lyn,

Thanks for the message. I'm not sure why this isn't working for you using the console but you should be able to view the files in here using command line:
`gustil -u my-project ls gs://mito-wgs-public-2023`

For GWAS Catalog, you can find the files if you search for the name of the paper, or using the PMID: https://www.ebi.ac.uk/gwas/publications/37587338

Best,
Rahul

**Comment by biolyn** [comment]
Thanks Rahul! Then, I can download from GWAS Catalog.
